# Spring Boot application configuration
spring:
  # Application name
  application:
    name: working-capital-management
  
  # Database configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Flyway migration configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Jackson JSON configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  
  # Multipart file upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # SQL initialization configuration
  sql:
    init:
      mode: never

# Server configuration
server:
  port: 5000
  compression:
    enabled: true
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Logging configuration
logging:
  level:
    org.springframework: INFO
    com.fintech.wcm: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

# Application-specific configuration
app:
  # JWT configuration
  jwt:
    secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    expiration: 86400000  # 24 hours in milliseconds
  
  # Scheduling configuration
  scheduling:
    enable: true
  
  # Swagger UI custom path
  swagger-ui:
    path: /swagger-ui.html
  
  # Cors configuration
  cors:
    allowed-origins: http://localhost:5000
